"""empty message

Revision ID: 3b5cfff21ef3
Revises: 
Create Date: 2021-04-02 14:49:50.058609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Date
from projeto.model import Unidade


# revision identifiers, used by Alembic.
revision = '3b5cfff21ef3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('create schema gotodata')
    op.create_table('unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medida', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='gotodata'
    )
    op.bulk_insert(Unidade.__table__,
        [
            {'id':1, 'medida':'°C'},
            {'id':2, 'medida':'%'},
            {'id':3, 'medida':'km'},
            {'id':4, 'medida':'hPa'},
        ]
    )
    op.create_table('clima',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidade', sa.String(length=40), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('id_unidade_temp', sa.Integer(), nullable=True),
    sa.Column('umidade', sa.Integer(), nullable=True),
    sa.Column('id_unidade_umidade', sa.Integer(), nullable=True),
    sa.Column('visibilidade', sa.Float(), nullable=True),
    sa.Column('id_unidade_vis', sa.Integer(), nullable=True),
    sa.Column('pressao', sa.Integer(), nullable=True),
    sa.Column('id_unidade_pressao', sa.Integer(), nullable=True),
    sa.Column('horario', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_unidade_pressao'], ['gotodata.unidade.id'], ),
    sa.ForeignKeyConstraint(['id_unidade_temp'], ['gotodata.unidade.id'], ),
    sa.ForeignKeyConstraint(['id_unidade_umidade'], ['gotodata.unidade.id'], ),
    sa.ForeignKeyConstraint(['id_unidade_vis'], ['gotodata.unidade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gotodata'
    )
    op.create_table('ibovespa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.Column('variacao', sa.Float(), nullable=True),
    sa.Column('id_unidade_variacao', sa.Integer(), nullable=True),
    sa.Column('minimo', sa.Integer(), nullable=True),
    sa.Column('maximo', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('horario', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_unidade_variacao'], ['gotodata.unidade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gotodata'
    )
    op.create_table('ibovespa_clima',
    sa.Column('id_clima', sa.Integer(), nullable=True),
    sa.Column('id_ibovespa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_clima'], ['gotodata.clima.id'], ),
    sa.ForeignKeyConstraint(['id_ibovespa'], ['gotodata.ibovespa.id'], ),
    schema='gotodata'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('drop schema gotodata')
    op.drop_table('ibovespa_clima', schema='gotodata')
    op.drop_table('ibovespa', schema='gotodata')
    op.drop_table('clima', schema='gotodata')
    op.drop_table('unidade', schema='gotodata')
    # ### end Alembic commands ###
